# Generated by Django 5.0.7 on 2025-05-25 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_rename_location_attendancerecord_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="company",
        ),
    ]
