# Generated by Django 5.0.7 on 2025-05-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_remove_employee_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="password",
            field=models.CharField(default="defaultpassword", max_length=128),
        ),
    ]
