# Generated by Django 5.0.7 on 2025-05-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_remove_employee_date_joined_employee_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
