# Generated by Django 5.0.7 on 2025-05-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_alter_employee_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="u_id",
        ),
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.IntegerField(
                blank=True, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
