# Generated by Django 5.0.7 on 2025-05-26 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_remove_employee_u_id_alter_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="employees.employee"
            ),
        ),
    ]
