# Generated by Django 5.0.7 on 2025-05-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0008_alter_attendancerecord_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="password",
        ),
    ]
