# Generated by Django 5.0.7 on 2025-05-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0009_remove_employee_email_remove_employee_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
